config/routes.rb
Rails.application.routes.draw do
  resources :bancos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get "sobre", to: "home#sobre"
#  get "contato", to: "contato#index"
#  get "contatos", to: "contato#lista"
#  post "contato/cadastrar", to: "contato#cadastrar"
#  get "contato/:id/editar", to: "contato#editar"
#  put  "contato/:id/atualizar", to: "contato#atualizar"
#  delete "contato/:id/excluir", to: "contato#excluir"
  
  resources :contatos
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banco.rb
class Banco < ApplicationRecord

include Bancos::Busca
    
end

app/models/concerns/bancos/busca.rb
module Bancos
    module Busca
        extend ActiveSupport::Concern
        included do
            scope :by_nome, ->(nome) { where("lower(nome) like ?", "%#{nome.downcase}%") if nome.present? }
            scope :by_localizacao, ->(localizacao) { where("lower(localizacao) like ?", "%#{localizacao.downcase}%") if localizacao.present? }
            scope :by_ano_fundacao, ->(ano_fundacao) { where("ano_fundacao::text like ?", "%#{ano_fundacao}%") if ano_fundacao.present? }
            scope :by_numero_agencias, ->(numero_agencias) { where("numero_agencias::text like ?", "%#{numero_agencias}%") if numero_agencias.present? }
            scope :by_email, ->(email) { where("lower(email) like ?", "%#{email.downcase}%") if email.present? }
        end
    end
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :set_banco, only: %i[ show edit update destroy ]
  before_action :hook_console, only: [:create, :update, :index]

  # GET /bancos or /bancos.json
  def index
    @bancos = BancoServiceQuery.busca_por_parametro(params)
  end

  # GET /bancos/1 or /bancos/1.json
  def show
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
  end

  # GET /bancos/1/edit
  def edit
  end

  # POST /bancos or /bancos.json
  def create
    @banco = Banco.new(banco_params)

    respond_to do |format|
      if @banco.save
        format.html { redirect_to banco_url(@banco), notice: "Banco was successfully created." }
        format.json { render :show, status: :created, location: @banco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bancos/1 or /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to banco_url(@banco), notice: "Banco was successfully updated." }
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1 or /bancos/1.json
  def destroy
    @banco.destroy

    respond_to do |format|
      format.html { redirect_to bancos_url, notice: "Banco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banco_params
      params.require(:banco).permit(:nome, :localizacao, :ano_fundacao, :numero_agencias, :email, :obs)
    end

    def hook_console
      puts "Parâmetros:"
      puts "==============================================================================================="
      puts params.inspect
      puts "==============================================================================================="
    end
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
  def index
  end

  def cadastrar
    nome = params["nome"]
    email = params["email"]
    observacao= params["observacao"]

    if nome.blank?
        flash["error"] = "O nome é obrigatório"
        return render "index"
    end

    if email.blank?
        flash["error"] = "O email é obrigatório"
        return render "index"
    end
    
    Contato.create(nome:nome, email:email, observacao:observacao)
    flash["success"] = "Contacto cadastrado com sucesso"
    redirect_to "/"
  end

  def lista
    @contatos = Contato.all.order(id: :asc)
  end

  def editar
    @contato = Contato.find(params[:id])
  end

  def atualizar
    @contato = Contato.find(params["id"])

        @contato.nome = params["nome"]
        @contato.email = params["email"]
        @contato.observacao = params["observacao"]
        
        if @contato.nome.blank?
            flash["error"] = "O nome é obrigatório"
            return render "editar"
        end

        if @contato.email.blank?
            flash["error"] = "O email é obrigatório"
            return render "editar"
        end

        @contato.save!

        flash["success"] = "Contato atualizado com sucesso"
        render json: @contato.to_json, status: 200
  end

  def excluir
    contato = Contato.find(params["id"])
    contato.destroy

    flash["success"] = "Contato excluido com sucesso"
    render json: {}, status: 204
  end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  def new
  end

  def create
      nome = params["contato"]["nome"]
      email = params["contato"]["email"]
      observacao = params["contato"]["observacao"]
      
      if nome.blank?
          flash["error"] = "O nome é obrigatório"
          return render "index"
      end

      if email.blank?
          flash["error"] = "O email é obrigatório"
          return render "index"
      end

      Contato.create!(nome: nome, email:email, observacao:observacao)

      flash["success"] = "Contato cadastrado com sucesso"
      redirect_to "/contatos"
  end

  def update
      @contato = Contato.find(params["id"])

      @contato.nome = params["contato"]["nome"]
      @contato.email = params["contato"]["email"]
      @contato.observacao = params["contato"]["observacao"]
      
      if @contato.nome.blank?
          flash["error"] = "O nome é obrigatório"
          return render "editar"
      end

      if @contato.email.blank?
          flash["error"] = "O email é obrigatório"
          return render "editar"
      end

      @contato.save!

      flash["success"] = "Contato atualizado com sucesso"
      redirect_to "/contatos"
      # render json: @contato.to_json, status: 200
  end

  def index
      @contatos = Contato.all.order(id: :asc)
      respond_to do |format|
          format.html
          format.json { render json: @contatos }
      end
  end

  def edit
      @contato = Contato.find(params[:id])
  end

  def destroy
      contato = Contato.find(params["id"])
      contato.destroy

      flash["success"] = "Contato excluido com sucesso"
      render json: {}, status: 204
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sobre
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bancos/_form.html.erb
<%= form_for(@banco, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @banco.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@banco.errors.count, "error") %> prohibited this banco from being saved:</h4>

      <ul>
      <% @banco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :localizacao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :localizacao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ano_fundacao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :ano_fundacao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :numero_agencias, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :numero_agencias, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :obs, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :obs, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bancos/edit.html.erb
<div class="page-header">
  <%= link_to bancos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @banco, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing banco</h1>
</div>

<%= render 'form' %>

app/views/bancos/index.html.erb
<div class="page-header">
  <%= link_to new_banco_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Banco
  <% end %>
  <h1>Listando bancos</h1>
</div>

<div>
  <form class="form-horizontal" action="/bancos" accept-charset="UTF-8" method="get">
    <div class="form-group">
      <label class="col-sm-1 control-label" for="aluno_nome">Nome</label>
      <div class="col-sm-11">
        <input class="form-control" type="text" name="nome" value="<%= params[:nome] %>" id="aluno_nome">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="aluno_email">Localização</label>
      <div class="col-sm-11">
      <input class="form-control" type="text" name="localizacao" value="<%= params[:localizacao] %>" id="localizacao">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="ano_fundacao">Ano de fundação</label>
      <div class="col-sm-11">
      <input class="form-control" type="text" name="ano_fundacao" value="<%= params[:ano_fundacao] %>" id="ano_fundacao">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="numero_agencias">Numero de Agencias</label>
      <div class="col-sm-11">
      <input class="form-control" type="text" name="numero_agencias" value="<%= params[:numero_agencias] %>" id="numero_agencias">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="email">Email</label>
      <div class="col-sm-11">
      <input class="form-control" type="email" name="email" value="<%= params[:email] %>" id="email">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="obs">Obs</label>
      <div class="col-sm-11">
        <input class="form-control" type="text" name="obs" value="<%= params[:obs] %>" id="obs">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-1 control-label" for="ids">ID´s por ,</label>
      <div class="col-sm-11">
        <input class="form-control" type="text" name="ids" value="<%= params[:ids] %>" id="ids">
      </div>
    </div>
    <div class="form-group">
    <div class="form-group col-sm-6">
      <label class="col-sm-3 control-label" for="ano_ini">Ano inicio</label>
      <div class="col-sm-9">
        <input class="form-control" type="text" name="ano_ini" value="<%= params[:ano_ini] %>" id="ano_ini">
      </div>
    </div>
    <div class="form-group col-sm-6">
      <label class="col-sm-3 control-label" for="ano_fim">Ano fim</label>
      <div class="col-sm-9">
        <input class="form-control" type="text" name="ano_fim" value="<%= params[:ano_fim] %>" id="ano_fim">
      </div>
    </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12" style="text-align:right">
        <input type="submit" value="Buscar" class="btn btn-primary" data-disable-with="Pesquisand...">
      </div>
    </div>
  </form>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Localizacao</th>
            <th>Ano fundacao</th>
            <th>Numero agencias</th>
            <th>Email</th>
            <th>Obs</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bancos) do |banco| %>
            <td><%= banco.id %></td>
            <td><%= banco.nome %></td>
            <td><%= banco.localizacao %></td>
            <td><%= banco.ano_fundacao %></td>
            <td><%= banco.numero_agencias %></td>
            <td><%= banco.email %></td>
            <td><%= banco.obs %></td>
            <td><%= link_to 'Show', banco %></td>
        <td><%= link_to 'Edit', edit_banco_path(banco) %></td>
        <td><%= link_to 'Destroy', banco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bancos/new.html.erb
<div class="page-header">
  <%= link_to bancos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New banco</h1>
</div>

<%= render 'form' %>

app/views/bancos/show.html.erb
<div class="page-header">
  <%= link_to bancos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_banco_path(@banco), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show banco</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @banco.nome %></dd>

  <dt>Localizacao:</dt>
  <dd><%= @banco.localizacao %></dd>

  <dt>Ano fundacao:</dt>
  <dd><%= @banco.ano_fundacao %></dd>

  <dt>Numero agencias:</dt>
  <dd><%= @banco.numero_agencias %></dd>

  <dt>Email:</dt>
  <dd><%= @banco.email %></dd>

  <dt>Obs:</dt>
  <dd><%= @banco.obs %></dd>

</dl>

app/views/contato/_form.html.erb
<form action="<%= url %>" method="post" onsubmit="<%= onsubmit %>">
          
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div class="form-group">
        <label for="nome">Nome *:</label>
        <input type="text" class="form-control" id="nome" name="nome" value="<%= contato.nome %>" placeholder="Digite seu nome" required>
    </div>

    <div class="form-group">
        <label for="email">E-mail *:</label>
        <input type="email" class="form-control" id="email" name="email" value="<%= contato.email %>" placeholder="Digite seu e-mail" required>
    </div>

    <div class="form-group">
        <label for="observacao">Observação:</label>
        <textarea class="form-control" id="observacao" name="observacao" placeholder="Digite sua observação" rows="4"><%= contato.observacao %></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

app/views/contato/editar.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Editando um contato</h1>
        <p class="lead text-body-secondary">
            Preencha o formulário abaixo:
        </p>

        <div style="text-align: left">

          <%= render "form", url:"/contato/#{@contato.id}/atualizar", onsubmit:"atualizar(event)", contato:@contato %>

        </div>
      </div>
    </div>
</section>

app/views/contato/lista.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Lista de contactos</h1>
        </p>
        <a href="/contato" class="btn btn-primary">Novo cadastro</a>
        <hr>
        <div style="text-align: left">
        <table class="table">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Email</th>
              <th>Observação</th>
              <th>Criado em</th>
              <th>Atualizado em</th>
              <th>Acções</th>
            </tr>
          </thead>
          <tbody>
            <% @contatos.each do |contato| %>
              <tr>
                <td><%= contato.nome %></td>
                <td><%= contato.email %></td>
                <td><%= contato.observacao %></td>
                <td><%= contato.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td><%= contato.updated_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td>
                    <a href="/contato/<%= contato.id%>/editar" class="btn btn-warning btn-acoes">Editar</a>
                    <a href="#" onclick="excluir('/contato/<%= contato.id %>/excluir')" class="btn btn-danger btn-acoes">Excluir</a>
                    </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        </div>
      </div>
    </div>
</section>

app/views/contatos/_form-rails.html.erb
<%= form_for contato do |f| %>

    <div class="form-group">
        <%= f.label :nome, "Nome *:" %>
        <%= f.text_field :nome, class: "form-control", placeholder: "Digite o nome", required: true %>    
    </div>

    <div class="form-group">
        <%= f.label :email, "E-mail *:" %>
        <%= f.email_field :email, class: "form-control", placeholder: "Digite seu e-mail", required: true %>
    </div>

    <div class="form-group">
        <%= f.label :observacao, "Observação:" %>
        <%= f.text_area :observacao, class: "form-control", placeholder: "Digite sua observação", rows: 4 %>
    </div>

    <%= f.submit "Enviar", class: "btn btn-primary" %>

<% end %>

app/views/contatos/edit.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Editando um contato</h1>
        <p class="lead text-body-secondary">
            Preencha o formulário abaixo:
        </p>

        <div style="text-align: left">
          <%= render "form-rails", contato:@contato %>
        </div>
      </div>
    </div>
</section>

app/views/contatos/index.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Lista de contactos</h1>
        </p>
        <a href="/contato" class="btn btn-primary">Novo cadastro</a>
        <hr>
        <div style="text-align: left">
        <table class="table">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Email</th>
              <th>Observação</th>
              <th>Criado em</th>
              <th>Atualizado em</th>
              <th>Acções</th>
            </tr>
          </thead>
          <tbody>
            <% @contatos.each do |contato| %>
              <tr>
                <td><%= contato.nome %></td>
                <td><%= contato.email %></td>
                <td><%= contato.observacao %></td>
                <td><%= contato.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td><%= contato.updated_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td>
                    <a href="/contatos/<%= contato.id%>/edit" class="btn btn-warning btn-acoes">Editar</a>
                    <a href="#" onclick="excluir('<%= contato_path(contato) %>')" class="btn btn-danger btn-acoes">Excluir</a>
                    </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        </div>
      </div>
    </div>
</section>

app/views/contatos/new.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Entre em contato conosco</h1>
        <p class="lead text-body-secondary">
            Preencha o formulário abaixo:
        </p>

        <div style="text-align: left">

          <%= render "form-rails", contato:Contato.new %>
          
        </div>
      </div>
    </div>
</section>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/sobre.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Sobre o Treinamento Pagaso</h1>
        <div class="lead text-body-secondary" style="text-align:left">
            <h3>Bem-vindo ao Treinamento Pagasó: Desenvolvimento Web com Ruby on Rails!</h3>
            <p>Neste emocionante treinamento, estou empolgado em compartilhar com vocês os fundamentos e as melhores práticas do desenvolvimento web utilizando a poderosa linguagem de programação Ruby em conjunto com o framework Rails. Prepare-se para mergulhar em um universo de possibilidades e construir aplicações web robustas, eficientes e elegantes!</p>
            <p>Durante nossas aulas, iremos abordar os seguintes tópicos:</p>
            <ul>
                <li>Configuração do ambiente de desenvolvimento Ruby e Rails;</li>
                <li>Criação de modelos, migrações e relacionamentos entre bancos de dados;</li>
                <li>Implementação de rotas e controle de requisições;</li>
                <li>Criação de visões dinâmicas e utilização de layouts;</li>
                <li>Autenticação e autorização de usuários;</li>
                <li>Uso de formulários e validações de dados;</li>
                <li>Implementação de testes automatizados para garantir a qualidade do código;</li>
                <li>Integração com APIs externas e serviços web;</li>
                <li>Otimização de desempenho e escalabilidade de aplicações Rails;</li>
                <li>Boas práticas de segurança e prevenção de vulnerabilidades.</li>
            </ul>
            <p>Ao longo do treinamento, não apenas aprenderemos a desenvolver com Ruby on Rails, mas também compreenderemos os princípios e padrões de design por trás do framework, permitindo-nos construir aplicações web elegantes e bem estruturadas.</p>
            <p>Além disso, o treinamento será fortemente baseado em projetos práticos, onde vocês poderão aplicar imediatamente os conhecimentos adquiridos em aulas teóricas. Também incentivarei a colaboração e o trabalho em equipe, uma vez que a programação em equipe é uma habilidade essencial no mundo real.</p>
            <p>Não se esqueçam de que estarei disponível para responder a todas as suas perguntas e oferecer orientação personalizada durante todo o treinamento. Meu objetivo é ajudá-los a se tornarem desenvolvedores web confiantes e habilidosos, prontos para enfrentar desafios reais no mercado de trabalho.</p>
            <p>Estou empolgado com o progresso que faremos juntos e estou confiante de que, ao final deste treinamento, vocês terão as habilidades necessárias para criar aplicativos web incríveis usando Ruby on Rails.</p>
            <p>Vamos embarcar nesta jornada de aprendizado e construção de futuros brilhantes juntos!</p>
        </div>
      </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Treinamento Pagaso</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pagaso", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li <% if params[:controller] == "home" && params[:action] == "index" %> class="active" <% end %>><a href="/">Home</a></li>
          <li <% if params[:controller] == "sobre" && params[:action] == "sobre" %> class="active" <% end %>><a href="/sobre">Sobre</a></li>
          <li <% if params[:controller] == "contato" && params[:action] == "index" %> class="active" <% end %>><a href="/contato">Contato</a></li>
          <li <% if params[:controller] == "contatos" && params[:action] == "index" %> class="active" <% end %>><a href="/contatos">Contatos</a></li>
          <li <% if params[:controller] == "bancos" && params[:action] == "index" %> class="active" <% end %>><a href="/bancos">Bancos</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error || name == "error" ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/index.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5" style="text-align: center;">
      <div class="col-lg-6 col-md-8 mx-auto" style="float: none;display: inline-block;">
        <h1 class="fw-light">Entre em contato conosco</h1>
        <p class="lead text-body-secondary">
            Preencha o formulário abaixo:
        </p>

        <div style="text-align: left">

          <form action="/contato/cadastrar" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

            <div class="form-group">
              <label for="nome">Nome *:</label>
              <input type="text" class="form-control" id="nome" name="nome" placeholder="Digite seu nome" required>
            </div>

            <div class="form-group">
              <label for="email">E-mail *:</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Digite seu e-mail" required>
            </div>

            <div class="form-group">
              <label for="observacao">Observação:</label>
              <textarea class="form-control" id="observacao" name="observacao" placeholder="Digite sua observação" rows="4"></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
</section>